---
title: "FrenchNuclearOutput"
author: "GeoffRussell"
date: "2024-10-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

https://www.eea.europa.eu/en/analysis/indicators/drought-impact-on-ecosystems-in-europe

```{r}
houtput<-c(66.0,63.8,62.1,72.5,66.4,74.3,60.4,58.9,59.6,51.5,56.3,57.6,63.7,57.0,62.7,44.8,58.8,70.8,62.8,54.6,59.9,49.0,63.9,56.0,61.7,58.7,44.3,55.5)



year<-seq(1996,2023,1)
gasoutput<-c(4.1,4.9,5.0,7.7,11.5,15.1,18.4,19.4,21.0,23.1,21.8,22.0,21.9,20.5,23.8,29.5,24.8,21.1,15.8,24.4,38.0,43.4,33.5,41.7,37.0,35.2,47.1,32.3)
noutput<-c(397.3,395.5,388.0,394.2,415.2,421.1,436.8,441.1,448.2,451.5,450.2,439.7,439.4,409.7,428.5,442.4,425.4,423.7,436.5,437.4,403.2,398.4,412.9,399.0,353.8,379.4,294.7,338.2)
coaloutput<-c(31.0,25.9,37.3,33.1,30.9,23.9,27.0,29.3,27.2,30.7,26.4,28.2,26.4,24.0,26.3,17.8,18.0,21.1,9.4,9.5,7.8,10.3,6.2,1.6,1.4,4.1,3.1,0.9)
drought<-c(
  F,F,F,F,F,F,F,T,F,F,
  F,F,F,F,F,F,T,F,F,F,
  F,F,T,T,F,F,T,F)
df<-data_frame(year=year,noutput=noutput,drought=drought,houtput=houtput,gasoutput=gasoutput,coutput=coaloutput)
p<-df |> ggplot()+
  geom_col(aes(year,noutput,fill=drought))+
  geom_line(aes(year,houtput),color="blue",size=1)+
  geom_line(aes(year,gasoutput),color="black",size=1)+
  geom_line(aes(year,coutput),color="red",size=1)+
  annotate("text",x=2003,y=40,label="Gas",color="black")+
  annotate("text",x=2005,y=80,label="Hydro",color="blue")+
  annotate("text",x=1998,y=50,label="Coal",color="red")+
  labs(title="French nuclear output\n(Data: Energy Institute; Drought;European Env Agency)")
p
png("french-nuclear-output-droughts.png",width=3000,height=2000,units="px",res=300)
print(p)
dev.off()
```

