---
title: "nemlog-analyse-wind"
author: "GeoffRussell"
date: "2025-01-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(RcppRoll)
dopng<-function(name,p,w=2200,h=1300) {
  png(name,width=w,height=h,units="px",res=300,type="cairo-png")
  print(p)
  dev.off()
}
comma<-function(x) prettyNum(signif(x,digits=5),big.mark=",")
options(scipen=99999)
```


```{r}
dfwmayonly<-read_csv("NEM WIND from NEM_WIND (MW) _ Period_ 2024-04-30 23_30 to 2024-05-31 23_29 _ GPE NEMLog-data-2025-01-18 19_43_30.csv") |> 
  rename(time=Time,wind=`WIND NEM`) |> mutate(pow=wind)
dfw<-read_csv("NEM WIND from NEM_WIND (MW) _ Period_ 2024-01-01 00_30 to 2025-01-01 00_29 _ GPE NEMLog-data-2025-01-16 08_54_17.csv") |> 
  rename(time=Time,wind=`WIND NEM`) |> mutate(pow=wind)
dfs<-read_csv("NEM SOLAR from NEM_SOLAR (MW) _ Period_ 2024-01-01 00_30 to 2025-01-01 00_29 _ GPE NEMLog-data-2025-01-16 13_57_16.csv") |> 
  rename(time=Time,solar=`SOLAR NEM`) |> mutate(pow=solar)
dfrts<-read_csv("NEM SOLAR_ROOFTOP_PV from NEM_SOLAR_ROOFTOP_PV (MW) _ Period_ 2024-01-01 00_30 to 2025-01-01 00_29 _ GPE NEMLog-data-2025-01-16 13_58_26.csv") |>
  rename(time=Time,rts=`SOLAR_ROOFTOP_PV NEM`)|> mutate(pow=rts)

df<-bind_cols(dfw,dfs,dfrts) |> mutate(time=`time...1`) |> select(time,solar,wind,rts) |> mutate(pow=solar+wind) 
```

```{r}
ndays=3
meanpow=mean(df$pow)

findmin<-function(v,wlen,p) {
  rs<-roll_sum(v,n=wlen,fill=0,align="left")
  names(rs)=seq(1,length(rs))
  #print(v)
  #print(rs)
  mm=9999999999
  nm=""
  for(i in seq(1,length(rs))) {
    if (p(rs[i]) && rs[i]<mm) {
      nm=names(rs)[i]
      mm=rs[i]
    }
  }
  tibble(min=mm,ix=as.numeric(nm),maxrs=max(rs[rs>0]),meanrs=mean(rs[rs>0]))
}


dostats<-function(df,tag,meanpow,ndays=7,doplot=F) {
  pdays=nrow(df)/(12*24)
  pos=as.integer(0.1*nrow(df))
  t<-findmin(df$pow/12,12*ndays*24,function(v) {v>1})
  #print(t)
  minrollsum=t$min
  ixmin=t$ix
  print(paste0("Start of MinWeek: ",df$time[ixmin]))
  maxrollsum=t$maxrs
  meanrollsum=t$meanrs
  periodoutput<-sum(df$pow/12)
  print(paste0("Period days : ",pdays," days"))
  print(paste0("Window days : ",ndays," days"))
  print(paste0("Period output : ",comma(periodoutput)," MWh"))
  print(paste0("Theoretical period output: ",comma(meanpow*24*pdays)," MWh"))
  print(paste0("Weekly min ",tag,": ",comma(minrollsum)," MWh"))
  print(paste0("Weekly max ",tag,": ",comma(maxrollsum)," MWh"))
  print(paste0("Weekly mean ",tag,": ",comma(meanrollsum)," MWh"))
  print(paste0("Weekly theoretical mean : ",comma(meanpow*24*ndays)," MWh"))
  if (doplot) {
    p<-df |> ggplot() + 
      geom_rect(aes(xmin=df$time[ixmin],xmax=df$time[ixmin+12*24*ndays],ymin=0,ymax=Inf),fill="grey80",alpha=0.1) +
      geom_line(aes(x=time,y=pow),color="blue") + labs(title=paste0("NEM output ",tag,"\nMinimum window shaded\nWindow length: ",ndays," days")) +
      annotate('text',x=df$time[pos],y=7000,hjust=0,label=paste0("Minimum window output\n",comma(100*minrollsum/(meanpow*24*ndays)),"% of annual weekly mean"))
    return (p)
  }
}
p<-dostats(dfw,"(2024 - Wind)",mean(dfw$pow),7,T)
p
```
```{r}
dfwmay<-dfw |> filter(time>=ymd("2024-05-01") & time<ymd("2024-06-01"))
dfwjune<-dfw |> filter(time>=ymd("2024-06-01") & time<ymd("2024-07-01"))
dfwjuly<-dfw |> filter(time>=ymd("2024-07-01") & time<ymd("2024-08-01"))

dfmay<-df |> filter(time>=ymd("2024-05-01") & time<ymd("2024-06-01"))
dfjune<-df |> filter(time>=ymd("2024-06-01") & time<ymd("2024-07-01"))
dfjuly<-df |> filter(time>=ymd("2024-07-01") & time<ymd("2024-08-01"))


pmaywind<-dostats(dfwmay,"(May wind)",mean(dfw$pow),7,T)
pmaywind
pjunewind<-dostats(dfwjune,"(June wind)",mean(dfw$pow),7,T)
pjunewind
pjulywind<-dostats(dfwjuly,"(July wind)",mean(dfw$pow),7,T)
pjulywind

dopng("NEMWind-May2024.png",pmaywind)
dopng("NEMWind-June2024.png",pjunewind)
dopng("NEMWind-July2024.png",pjulywind)
pjune<-dostats(dfjune,"(June wind+solar)",mean(df$pow),2,T)
pmay1<-dostats(dfmay,"(May wind+solar)",mean(df$pow),1,T)
pmay2<-dostats(dfmay,"(May wind+solar)",mean(df$pow),2,T)
pmay7<-dostats(dfmay,"(May wind+solar)",mean(df$pow),7,T)
pjuly<-dostats(dfjuly,"(July wind+solar)",mean(df$pow),2,T)
pjune
pjuly
pmay1
pmay2
pmay7
dopng("NEMWindSolar-May2024.png",pmay7)
```
