---
title: "testfunction"
author: "GeoffRussell"
date: "2025-01-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(RcppRoll)
comma<-function(x) prettyNum(signif(x,digits=3),big.mark=",")
```

```{r}
percIncrease<-function(desc,x,z) {
  if (z>x) {
    cat(paste0("Increase (",desc,") in percentage from ",x, " to ",z," is ",comma(100*(z/x-1)),"%\n"))
  }
  else {
    cat("Second argument must be greater than first")
  }
}
percIncrease("European LNG imports 2021 to 2023",107.5,169.1)

percReduction<-function(desc,x,z) {
  if (z<x) {
    cat(paste0("Reduction (",desc,") in percentage from ",x, " to ",z," is ",comma(100*(1-z/x)),"%\n"))
  }
  else {
    cat("Second argument must be less than first")
  }
}
percReduction("Global gas trade 2021 to 2023",1020.4,936.4)
```

```{r}
df<-tibble(r=runif(100))
rs<-roll_sum(df$r,n=6)
str(rs)
names(rs)=seq(1,length(rs))
findmin<-function(v,wlen,p) {
  rs<-roll_sum(v,n=wlen,fill=0,align="left")
  names(rs)=seq(1,length(rs))
  print(v)
  print(rs)
  mm=9999999999
  nm=""
  for(i in seq(1,length(rs))) {
    if (p(rs[i]) && rs[i]<mm) {
      nm=names(rs)[i]
      mm=rs[i]
    }
  }
  tibble(min=mm,ix=nm)
}
df<-tibble(r=runif(50))
df
t<-findmin(df$r,6,function(v) {v>1})
t
```
rs
rs>2
mins<-min(rs[rs>1])
minix<-which(rs==mins)
mins
minix
s<-seq(1,length(rs))
rs[s>=minix & s<=minix+6]=1
rs
mins2<-min(rs[rs>1])
minix2<-which(rs==mins2)
mins2
minix2

```
s<-seq(1,length(rs))
mins
minix
rs[s>=minix & s<=minix+6]=1
rs
mins2<-min(rs[rs>1])
minix2<-which.min(rs[rs>1])
mins2
minix2
rs[rs>1]
```

```{r data}
df<-tribble(
  ~Year,~'Reference Unit Power (MWe)',~'Electricity Supplied (GWh)',~'Annual Time Online (Hours)',
  2000, 800, 2000.8, 2698,
  2001, 850, 2100.8, 3698,
  2002, 850, 2300.8, 4698
)



ccc<-c('Reference Unit Power (MWe)','Annual Time Online (Hours)','Electricity Supplied (GWh)')
df |> pivot_longer(cols=ccc) |> select(Yeark)
```




